//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAoQuan
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Admin
    {
        public string tendn { get; set; }
        public int id { get; set; }
        public string pass { get; set; }
    }
}
